[
    { "Phrase": "dinner", "Answer": "hapunan" },
{ "Phrase": "Where did you go on vacation", "Answer": "Saan ka nag bakasyon" },
{ "Phrase": "Where are you going on vacation", "Answer": "Saan ka magbabakasyon -future" },
{ "Phrase": "Where's my halo halo", "Answer": "Nasa elang halo halo" },
{ "Phrase": "I live here", "Answer": "Dito ako nakatira" },
{ "Phrase": "We live in Boracay", "Answer": "Sa Boracay kami nakatira" },
{ "Phrase": "How old are you", "Answer": "Ilan taon kana" },
{ "Phrase": "you stink", "Answer": "ang baho" },
{ "Phrase": "you shit", "Answer": "tae ka" },
{ "Phrase": "you fart", "Answer": "utot mo" },
{ "Phrase": "you cook", "Answer": "magluto kana" },
{ "Phrase": "What's your name", "Answer": "anon pangalan mo" },
{ "Phrase": "I love you", "Answer": "mahal kita" },
{ "Phrase": "how are you", "Answer": "kumusta" },
{ "Phrase": "good", "Answer": "mabuti" },
{ "Phrase": "I am learning Tagalog", "Answer": "Akoy naga aaral nang Tagalog" },
{ "Phrase": "How was your vacation", "Answer": "Kumusta ang bakasyon mo" },
{ "Phrase": "Fun! I went to the island gigantes", "Answer": "Masaya! Pumunta ako sa isla gigantes" },
{ "Phrase": "I'm at home", "Answer": "Nasa bahay lang ako" },
{ "Phrase": "I", "Answer": "Ayoko" },
{ "Phrase": "one", "Answer": "Isa" },
{ "Phrase": "two", "Answer": "Dalawa" },
{ "Phrase": "three", "Answer": "Tatlo" },
{ "Phrase": "four", "Answer": "Apat" },
{ "Phrase": "five", "Answer": "Lima" },
{ "Phrase": "six", "Answer": "Anim" },
{ "Phrase": "seven", "Answer": "Pito" },
{ "Phrase": "eight", "Answer": "Walo" },
{ "Phrase": "nine", "Answer": "Siyam" },
{ "Phrase": "ten", "Answer": "Sampu" }
]